[package]
name = "rust_code_organization"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
rand = "0.8.4"

[dev-dependencies]
criterion = "0.3"  # Per benchmark

[build-dependencies]
cc = "1.0"  # Per compilare codice C