[package]
name = "rust_code_organization"
version = "0.1.0"
edition = "2021"

# Definizione crate binari
[[bin]]
name = "main_bin"
path = "src/main.rs"

[[bin]]
name = "bin_v1"
path = "src/bin/bin_v1.rs"

[[bin]]
name = "bin_v2"
path = "src/bin/bin_v2.rs"